[package]
name = "ray-rs"
version = "0.0.0"
authors = ["Jonathan Chuang"]
license = "Apache-2.0"
edition = "2018"
publish = true
repository = "https://github.com/ray-project/ray"
description = "Ray Rust language worker API"

[dependencies]
paste = "1.0.6"
uniffi = "0.16.0"
lazy_static = "1.4.0"
rmp-serde = "0.15.5"
serde = "1.0.132"
libloading = "0.7.2"
libc = "0.2.112"
ctor = "0.1.21"
tokio = { version = "1.16.1", optional = true, features = ["rt", "rt-multi-thread", "time", "sync", "net"] }
#path = "../../../tokio/tokio",
async-ffi = "0.4.0"
# ray-rs-sys = "0.0.0"
ray-rs-sys = { path="../ray-rs-sys" }

[build-dependencies]
rustc_version = "0.4.0"

[features]
async = ["tokio"]
