[package]
name = "tokio-time-sleep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.16.1", features = ["rt", "time"] }
#path = "../../../../../tokio/tokio",version = "1.16.1"
