[package]
name = "tokio-time-sleep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { path = "../../../../../tokio/tokio", features = ["rt", "rt-multi-thread", "time", "sync", "net"] }
#path = "../../../../../tokio/tokio",version="1.16.1"
