version: 2
updates:
  # Tune/SGD/Doc requirements
  - package-ecosystem: "pip"
    # The requirements base directory currently only contains tune requirements.
    # If we want to add more requirements here (Core, RLlib, etc.), then we should make subdirectories for each one.
    directory: "/python/requirements"
    schedule:
      # TODO(amogkam) change this to weekly after some initial validation.
      interval: "daily"
      # 8 PM
      time: "20:00"
      # Use Pacific Standard Time
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "[Tune]"
      include: "scope"
    # Only 3 upgrade PRs at a time.
    open-pull-requests-limit: 3
    reviewers:
      - "ray-project/ray-tune"
