base_image: "anyscale/ray:pinned-nightly-py37"
env_vars: { }
debian_packages:
  - curl

python:
  pip_packages:
    - pytest
    - xgboost_ray
    - dask
  conda_packages: [ ]

post_build_cmds:
  - pip uninstall -y ray || true
  - pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
