base_image: "anyscale/ray-ml:pinned-nightly-py37-gpu"
env_vars: { }
debian_packages:
  - curl

python:
  pip_packages:
    - pytest
    - torch
    - torchvision
    - fastapi
    - uvicorn
    - tblib
  conda_packages: [ ]

post_build_cmds:
  - pip uninstall -y ray || true
  - pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
