base_image: {{ env["RAY_IMAGE_ML_NIGHTLY_GPU"] | default("anyscale/ray-ml:nightly-py39-gpu") }}
env_vars: {}
debian_packages: []

aws:
    # Fix the volume size so that IOPS is constant even if the default changes.
    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
            # 150GB is the default in Anyscale.
            VolumeSize: 150

python:
  pip_packages: []
  conda_packages: []

post_build_cmds:
  - pip uninstall -y ray || true && pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  - {{ env["RAY_WHEELS_SANITY_CHECK"] | default("echo No Ray wheels sanity check") }}
