#server:
  #http_listen_port: 9080
  #grpc_listen_port: 0

positions:
  filename: /data/loki/positions.yaml

#clients:
  #- url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /tmp/ray/session_latest/logs/*
