base_image: "anyscale/ray-ml:pinned-nightly-py37"
env_vars: {}
debian_packages: []

python:
  pip_packages: []
  conda_packages: []

post_build_cmds:
  - pip uninstall -y ray
  - pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  - pip3 install -U ray[default]
  - pip3 install sklearn
  - echo {{env["DATESTAMP"]}}
