# Head node
head_node_type:
  name: head
  instance_type: m5.2xlarge

# Worker nodes
worker_node_types:
  - name: gpu-workers
    instance_type: g5.4xlarge
    min_workers: 8
    max_workers: 8  

auto_select_worker_config: false
flags:
  allow-cross-zone-autoscaling: true
