base_image: {{ env["RAY_IMAGE_NIGHTLY_CPU"] | default("anyscale/ray:nightly-py37") }}
env_vars: {"RAY_gcs_server_rpc_server_thread_num": "8"}
debian_packages: []

python:
  pip_packages: []
  conda_packages: []

post_build_cmds:
  - pip uninstall -y ray
  - pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  - pip3 install -U ray[default]
  - echo {{env["DATESTAMP"]}}
  - {{ env["RAY_WHEELS_SANITY_CHECK"] | default("echo No Ray wheels sanity check") }}
