cloud_id: cld_kvedZWag2qA8i5BjxUevf5i7

region: us-west-2

head_node_type:
    name: head_node
    instance_type: m5.16xlarge

worker_node_types:
   - name: worker_node
     instance_type: m5.xlarge
     min_workers: 250
     max_workers: 250
     use_spot: false
