base_image: "anyscale/ray-ml:pinned-nightly-py37-gpu"
env_vars: {}
debian_packages: []

python:
  pip_packages: []
  conda_packages: []

post_build_cmds:
  - pip uninstall -y ray
  - pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  - pip3 install ray[tune]
  - pip3 install torch torchvision ipdb
  - /home/ray/anaconda3/bin/python -m pip uninstall -y numpy
  - rm -rf /home/ray/anaconda3/lib/python3.7/site-packages/numpy
  - /home/ray/anaconda3/bin/pip install numpy==1.19.5
  - git clone https://github.com/NVIDIA/apex && cd apex && pip install -v --no-cache-dir  ./
