base_image: "anyscale/ray-ml:pinned-nightly-py37-gpu"
env_vars: {}
debian_packages:
  - libglib2.0-0
  - unrar
  - curl
  - unzip
  - gcc
  - python3-dev

python:
  pip_packages:
    # Atari support.
    - gym[atari]
    - atari_py
    # PyBullet support.
    - pybullet
    # Pin this to 2.4.3 so it'll work with CUDA=11.0.
    - tensorflow==2.4.3
  conda_packages: []

post_build_cmds:
  - pip uninstall -y numpy ray || true
  - sudo rm -rf /home/ray/anaconda3/lib/python3.7/site-packages/numpy
  - pip3 install numpy==1.19.5 || true
  - pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  # Install Atari ROMs.
  - wget http://www.atarimania.com/roms/Roms.rar
  - unrar x Roms.rar
  - python -m atari_py.import_roms .
