base_image: {{ env["RAY_IMAGE_ML_NIGHTLY_GPU"] | default("anyscale/ray-ml:nightly-py37-gpu") }}
env_vars: {}
debian_packages:
  - unzip
  - zip

python:
  # These dependencies should be handled by requirements_rllib.txt and
  # requirements_ml_docker.txt
  pip_packages:
      - gym
  conda_packages: []

post_build_cmds:
  - pip3 uninstall -y ray || true && pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  - {{ env["RAY_WHEELS_SANITY_CHECK"] | default("echo No Ray wheels sanity check") }}
  # TODO(jungong): remove once nightly image gets upgraded.
  - pip install -U pybullet==3.2.0
  # Clone the rl-experiments repo for offline-RL files.
  - git clone https://github.com/ray-project/rl-experiments.git
  - cp rl-experiments/halfcheetah-sac/2021-09-06/halfcheetah_expert_sac.zip ~/.
