base_image: "anyscale/ray-ml:pinned-nightly-py37-gpu"
env_vars: {}
debian_packages: []

python:
  # These dependencies should be handled by requirements_rllib.txt and
  # requirements_ml_docker.txt
  pip_packages: []
  conda_packages: []

post_build_cmds:
  - pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  # Clone the rl-experiments repo for offline-RL files.
  - git clone https://github.com/ray-project/rl-experiments.git
  - cp rl-experiments/halfcheetah-sac/2021-09-06/halfcheetah_expert_sac.zip ~/.
