name: "ray-py$PYTHON_VERSION-tpu-base$ARCH_SUFFIX"
froms: ["ubuntu:22.04"]
dockerfile: docker/base-deps/Dockerfile
srcs:
  - python/requirements_compiled.txt
  - python/requirements_compiled_py$PYTHON_VERSION.txt
  - python/deplocks/base_deps/ray_base_deps_tpu_py$PYTHON_VERSION.lock
build_args:
  - PYTHON_VERSION
  - BASE_IMAGE=ubuntu:22.04
  - PYTHON_DEPSET=python/deplocks/base_deps/ray_base_deps_tpu_py$PYTHON_VERSION.lock
tags:
  - cr.ray.io/rayproject/ray-py$PYTHON_VERSION-tpu-base$ARCH_SUFFIX
