[project]
name = "default"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.9",
    "doggos",
    "ipykernel>=6.30.1",
    "ipywidgets==8.1.3",
    "matplotlib==3.10.0",
    "mlflow==3.1.0",
    "ray[data,serve,train,tune]",
    "scikit-learn==1.6.0",
    "torch==2.7.1",
    "transformers==4.52.3",
]

[tool.uv.sources]
ray = { url = "http://localhost:9478/ray/ray-2.48.0-cp312-cp312-manylinux2014_x86_64.whl" }
doggos = { path = "doggos" }
