name: "ray-slim-py$PYTHON_VERSION-cpu-base$ARCH_SUFFIX"
froms: ["ubuntu:22.04"]
dockerfile: docker/base-slim/Dockerfile
srcs:
  - python/requirements_compiled.txt
  - python/deplocks/base_slim/$REQUIREMENTS_FILE
build_args:
  - PYTHON_VERSION
  - BASE_IMAGE=ubuntu:22.04
  - PYTHON_DEPSET=python/deplocks/base_slim/$REQUIREMENTS_FILE
tags:
  - cr.ray.io/rayproject/ray-slim-py$PYTHON_VERSION-cpu-base$ARCH_SUFFIX
