name: "ray-slim-py$PYTHON_VERSION-cu$CUDA_VERSION-base$ARCH_SUFFIX"
froms: ["nvidia/cuda:$CUDA_VERSION-runtime-ubuntu22.04"]
dockerfile: docker/base-slim/Dockerfile
srcs:
  - python/requirements_compiled.txt
  - python/deplocks/base_slim/$REQUIREMENTS_FILE
build_args:
  - PYTHON_VERSION
  - BASE_IMAGE=nvidia/cuda:$CUDA_VERSION-runtime-ubuntu22.04
  - PYTHON_DEPSET=python/deplocks/base_slim/$REQUIREMENTS_FILE
tags:
  - cr.ray.io/rayproject/ray-slim-py$PYTHON_VERSION-cu$CUDA_VERSION-base$ARCH_SUFFIX
