name: "oss-ci-base_test-aarch64"
froms: ["ubuntu:focal"]
dockerfile: ci/docker/base.test.Dockerfile
srcs:
  - ci/env/install-bazel.sh
  - ci/env/install-miniforge.sh
  - ci/suppress_output
  - .bazelversion
build_args:
  - BUILDKITE_BAZEL_CACHE_URL
  - PYTHON=3.10
tags:
  - cr.ray.io/rayproject/oss-ci-base_test-aarch64
