name: "datadocgpubuild-py$PYTHON"
froms: ["cr.ray.io/rayproject/oss-ci-base_ml-py$PYTHON"]
dockerfile: ci/docker/data.base.build.Dockerfile
srcs:
  - python/deplocks/ci/data-doc-ci_depset_py$PYTHON.lock
build_args:
  - DOCKER_IMAGE_BASE_BUILD=cr.ray.io/rayproject/oss-ci-base_ml-py$PYTHON
  - IMAGE_TYPE=doc
tags:
  - cr.ray.io/rayproject/datadocgpubuild-py$PYTHON
