name: "data9build-py$PYTHON"
froms: ["cr.ray.io/rayproject/oss-ci-base_ml-py$PYTHON"]
dockerfile: ci/docker/data.base.build.Dockerfile
srcs:
  - python/deplocks/ci/data-v9-pyarrow-ci_depset_py$PYTHON.lock
build_args:
  - DOCKER_IMAGE_BASE_BUILD=cr.ray.io/rayproject/oss-ci-base_ml-py$PYTHON
  - IMAGE_TYPE=pyarrow-v9
tags:
  - cr.ray.io/rayproject/data9build-py$PYTHON
