name: "datatfxbslbuild-py$PYTHON"
froms: ["cr.ray.io/rayproject/oss-ci-base_test-py$PYTHON"]
dockerfile: ci/docker/data-tfxbsl.build.Dockerfile
srcs:
  - ci/env/install-dependencies.sh
  - python/requirements.txt
  - python/requirements_compiled.txt
  - python/requirements/test-requirements.txt
  - python/requirements/ml/data-requirements.txt
  - python/requirements/ml/data-test-requirements.txt
build_args:
  - DOCKER_IMAGE_BASE_BUILD=cr.ray.io/rayproject/oss-ci-base_test-py$PYTHON
  - ARROW_VERSION=14.*
tags:
  - cr.ray.io/rayproject/datatfxbslbuild-py$PYTHON
