name: "databuild-py$PYTHON"
froms: ["cr.ray.io/rayproject/oss-ci-base_ml-py$PYTHON"]
dockerfile: ci/docker/data.build.Dockerfile
srcs:
  - python/deplocks/ci/data-pyarrow-v20-ci_depset_py$PYTHON.lock
build_args:
  - DOCKER_IMAGE_BASE_BUILD=cr.ray.io/rayproject/oss-ci-base_ml-py$PYTHON
  - IMAGE_TYPE=pyarrow-v20
tags:
  - cr.ray.io/rayproject/databuild-py$PYTHON
