name: "datanbuild-py$PYTHON"
froms: ["cr.ray.io/rayproject/oss-ci-base_ml-py$PYTHON"]
dockerfile: ci/docker/data.build.Dockerfile
srcs:
  - ci/env/install-dependencies.sh
  - python/requirements.txt
  - python/requirements_compiled.txt
  - python/requirements/test-requirements.txt
  - python/requirements/ml/dl-cpu-requirements.txt
  - python/requirements/ml/data-requirements.txt
  - python/requirements/ml/data-test-requirements.txt
build_args:
  - DOCKER_IMAGE_BASE_BUILD=cr.ray.io/rayproject/oss-ci-base_ml-py$PYTHON
  - ARROW_VERSION=nightly
tags:
  - cr.ray.io/rayproject/datanbuild-py$PYTHON
