name: "llm$BUILD_VARIANT"
froms: ["cr.ray.io/rayproject/oss-ci-base_$BASE_TYPE-py$PYTHON"]
dockerfile: ci/docker/llm.build.Dockerfile
srcs:
  - ci/env/install-dependencies.sh
  - ci/env/install-llvm-binaries.sh
  - ci/suppress_output
  - python/deplocks/llm/rayllm_test_py311_cpu.lock
  - python/deplocks/llm/rayllm_test_py311_cu128.lock
tags:
  - cr.ray.io/rayproject/llm$BUILD_VARIANT
build_args:
  - DOCKER_IMAGE_BASE_BUILD=cr.ray.io/rayproject/oss-ci-base_$BASE_TYPE-py$PYTHON
  - RAY_CUDA_CODE=$RAY_CUDA_CODE
