name: "manylinux-cibase$JDK_SUFFIX$ARCH_SUFFIX"
froms:
  - quay.io/pypa/manylinux2014_$HOSTTYPE:2024-07-02-9ac04ee
srcs:
  - ci/build/build-manylinux-forge.sh
build_args:
  - BUILDKITE_BAZEL_CACHE_URL
  - RAYCI_DISABLE_JAVA
  - HOSTTYPE
dockerfile: ci/docker/manylinux.Dockerfile
