name: "ray-py$PYTHON_VERSION-tpu$ARCH_SUFFIX"
disable_caching: true
froms:
  - "cr.ray.io/rayproject/ray-py$PYTHON_VERSION-tpu-base$ARCH_SUFFIX"  # TPU base image with Python + deps
  - "cr.ray.io/rayproject/ray-wheel-py$PYTHON_VERSION$ARCH_SUFFIX"     # Ray wheel
dockerfile: ci/docker/ray-image.Dockerfile
build_args:
  - PYTHON_VERSION
  - ARCH_SUFFIX
  - PLATFORM=tpu
  - RAY_COMMIT=$BUILDKITE_COMMIT
  - RAY_VERSION
