name: "ray-cpp-core-py$PYTHON_VERSION$ARCH_SUFFIX"
froms: ["rayproject/manylinux2014:$MANYLINUX_VERSION-jdk-$HOSTTYPE"]
dockerfile: ci/docker/ray-cpp-core.Dockerfile
srcs:
  - .bazelversion
  - .bazelrc
  - WORKSPACE
  - BUILD.bazel
  - bazel/
  - thirdparty/
  - src/
  - cpp/
  - python/ray/__init__.py
  - python/ray/_raylet.pxd
  - python/ray/_raylet.pyi
  - python/ray/_raylet.pyx
  - python/ray/includes/
  - java/BUILD.bazel
  - java/dependencies.bzl
  - release/BUILD.bazel
  - release/requirements.txt
  - release/requirements_py310.txt
build_args:
  - PYTHON_VERSION
  - ARCH_SUFFIX
  - HOSTTYPE
  - MANYLINUX_VERSION
  - BUILDKITE_BAZEL_CACHE_URL
build_hint_args:
  - BUILDKITE_CACHE_READONLY
