# Ray Anyscale CUDA Image (for release tests)
# Installs ray wheel into the CUDA base-extra-testdeps image, which includes
# additional test dependencies.
#
# This produces the anyscale test image for GPU release tests.
#
name: "ray-anyscale-py$PYTHON_VERSION-cu$CUDA_VERSION$ARCH_SUFFIX"
disable_caching: true
froms:
  - "cr.ray.io/rayproject/ray-py$PYTHON_VERSION-cu$CUDA_VERSION-base-extra-testdeps"  # CUDA base with test deps
  - "cr.ray.io/rayproject/ray-wheel-py$PYTHON_VERSION$ARCH_SUFFIX"                    # Ray wheel
dockerfile: ci/docker/ray-image.Dockerfile
build_args:
  - PYTHON_VERSION
  - ARCH_SUFFIX
  - IMAGE_TYPE=ray
  - BASE_VARIANT=base-extra-testdeps
  - PLATFORM=cu$CUDA_VERSION
  - RAY_COMMIT=$BUILDKITE_COMMIT
  - RAY_VERSION
