name: "ray-py$PYTHON_VERSION-cu$CUDA_VERSION$ARCH_SUFFIX"
disable_caching: true
froms:
  - "cr.ray.io/rayproject/ray-py$PYTHON_VERSION-cu$CUDA_VERSION-base$ARCH_SUFFIX"  # CUDA base image
  - "cr.ray.io/rayproject/ray-wheel-py$PYTHON_VERSION$ARCH_SUFFIX"                 # Ray wheel
dockerfile: ci/docker/ray-image.Dockerfile
build_args:
  - PYTHON_VERSION
  - ARCH_SUFFIX
  - PLATFORM=cu$CUDA_VERSION
  - RAY_COMMIT=$BUILDKITE_COMMIT
  - RAY_VERSION
