name: "ray-core-py$PYTHON_VERSION$ARCH_SUFFIX"
froms: ["rayproject/manylinux2014:$MANYLINUX_VERSION-jdk-$HOSTTYPE"]
dockerfile: ci/docker/ray-core.Dockerfile
srcs:
  - .bazelversion
  - .bazelrc
  - WORKSPACE
  - BUILD.bazel
  - bazel/
  - thirdparty/
  - src/
  - gen_ray_pkg.py
  - python/ray/__init__.py
  - python/ray/_raylet.pxd
  - python/ray/_raylet.pyi
  - python/ray/_raylet.pyx
  - python/ray/includes/
  - java/BUILD.bazel
  - java/dependencies.bzl
  - release/BUILD.bazel
  - release/requirements_py310.txt
  - ci/build/container_resource_utils.py
build_args:
  - PYTHON_VERSION
  - ARCH_SUFFIX
  - BUILDKITE_BAZEL_CACHE_URL
  - HOSTTYPE
  - MANYLINUX_VERSION
build_hint_args:
  - BUILDKITE_CACHE_READONLY
  - IS_LOCAL_BUILD
