# Ray-LLM Anyscale CUDA Image (for release tests)
# Installs ray wheel into the ray-llm CUDA base-extra-testdeps image, which
# includes extra test dependencies.
#
# This produces the anyscale test image for ray-llm GPU release tests.
#
name: "ray-llm-anyscale-py$PYTHON_VERSION-cu$CUDA_VERSION$ARCH_SUFFIX"
disable_caching: true
froms:
  - "cr.ray.io/rayproject/ray-llm-py$PYTHON_VERSION-cu$CUDA_VERSION-base-extra-testdeps"  # ray-llm base with test deps
  - "cr.ray.io/rayproject/ray-wheel-py$PYTHON_VERSION$ARCH_SUFFIX"                        # Ray wheel
dockerfile: ci/docker/ray-image.Dockerfile
build_args:
  - PYTHON_VERSION
  - ARCH_SUFFIX
  - BASE_VARIANT=base-extra-testdeps
  - IMAGE_TYPE=ray-llm
  - PLATFORM=cu$CUDA_VERSION
  - RAY_COMMIT=$BUILDKITE_COMMIT
  - RAY_VERSION
