name: "ray-py$PYTHON_VERSION-cu$CUDA_VERSION-base-aarch64"
froms: ["nvidia/cuda:$CUDA_VERSION-devel-ubuntu22.04"]
dockerfile: docker/base-deps/Dockerfile
build_args:
  - PYTHON_VERSION
  - BASE_IMAGE=nvidia/cuda:$CUDA_VERSION-devel-ubuntu22.04
  - HOSTTYPE=aarch64
tags:
  - cr.ray.io/rayproject/ray-py$PYTHON_VERSION-cu$CUDA_VERSION-base-aarch64
