name: "rllib$BUILD_VARIANT-py$PYTHON"
froms: ["cr.ray.io/rayproject/oss-ci-base_$BASE_TYPE-py$PYTHON"]
dockerfile: ci/docker/rllib.build.Dockerfile
srcs:
  - ci/env/install-dependencies.sh
  - python/requirements.txt
  - python/requirements_compiled.txt
  - python/requirements/test-requirements.txt
  - python/requirements/ml/core-requirements.txt
  - python/requirements/ml/dl-cpu-requirements.txt
  - python/requirements/ml/dl-gpu-requirements.txt
  - python/requirements/ml/rllib-requirements.txt
  - python/requirements/ml/rllib-test-requirements.txt
build_args:
  - DOCKER_IMAGE_BASE_BUILD=cr.ray.io/rayproject/oss-ci-base_$BASE_TYPE-py$PYTHON
  - RAYCI_IS_GPU_BUILD
tags:
  - cr.ray.io/rayproject/rllib$BUILD_VARIANT-py$PYTHON
