name: "servebuild-py$PYTHON"
froms: ["cr.ray.io/rayproject/oss-ci-base_build-py$PYTHON"]
dockerfile: ci/docker/serve.build.Dockerfile
srcs:
  - python/deplocks/ci/serve_ci_depset_py$PYTHON.lock
build_args:
  - DOCKER_IMAGE_BASE_BUILD=cr.ray.io/rayproject/oss-ci-base_build-py$PYTHON
  - PYTHON=$PYTHON
tags:
  - cr.ray.io/rayproject/servebuild-py$PYTHON
