name: "servepydantic1build"
froms: ["cr.ray.io/rayproject/oss-ci-base_build-py3.10"]
dockerfile: ci/docker/serve.build.Dockerfile
srcs:
  - python/requirements.txt
  - python/requirements_compiled.txt
  - python/requirements/test-requirements.txt
build_args:
  - PYDANTIC_VERSION=1.10.12
  - DOCKER_IMAGE_BASE_BUILD=cr.ray.io/rayproject/oss-ci-base_build-py3.10
  - PYTHON=3.10
tags:
  - cr.ray.io/rayproject/servepydantic1build
