name: "servetracingbuild"
froms: ["cr.ray.io/rayproject/oss-ci-base_build-py3.10"]
dockerfile: ci/docker/serve.build.Dockerfile
srcs:
  - python/deplocks/ci/serve_tracing_depset_py3.10.lock
build_args:
  - ENABLE_TRACING=1
  - DOCKER_IMAGE_BASE_BUILD=cr.ray.io/rayproject/oss-ci-base_build-py3.10
  - PYTHON=3.10
  - IMAGE_TYPE=tracing
tags:
  - cr.ray.io/rayproject/servetracingbuild
