name: "$IMAGE_TYPE-py$PYTHON_VERSION-cpu-base-extra-testdeps"
froms: ["cr.ray.io/rayproject/$IMAGE_TYPE-py$PYTHON_VERSION-cpu-base-extra"]
dockerfile: release/ray_release/byod/byod.Dockerfile
srcs:
  - python/deplocks/base_extra_testdeps/ray_base_extra_testdeps_py${PYTHON_VERSION}.lock
build_args:
  - BASE_IMAGE=cr.ray.io/rayproject/$IMAGE_TYPE-py$PYTHON_VERSION-cpu-base-extra
  - PYTHON_VERSION=$PYTHON_VERSION
tags:
  - cr.ray.io/rayproject/$IMAGE_TYPE-py$PYTHON_VERSION-cpu-base-extra-testdeps
