name: "$IMAGE_TYPE-py$PYTHON_VERSION-cpu-base-extra-testdeps"
froms: ["cr.ray.io/rayproject/$IMAGE_TYPE-py$PYTHON_VERSION-cpu-base-extra"]
dockerfile: release/ray_release/byod/byod.Dockerfile
srcs:
  - $REQUIREMENTS_FILE
build_args:
  - BASE_IMAGE=cr.ray.io/rayproject/$IMAGE_TYPE-py$PYTHON_VERSION-cpu-base-extra
  - PIP_REQUIREMENTS=$REQUIREMENTS_FILE
tags:
  - cr.ray.io/rayproject/$IMAGE_TYPE-py$PYTHON_VERSION-cpu-base-extra-testdeps
