name: "$IMAGE_TYPE-py$PYTHON_VERSION-cu$CUDA_VERSION-base-extra-testdeps"
froms: ["cr.ray.io/rayproject/$IMAGE_TYPE-py$PYTHON_VERSION-cu$CUDA_VERSION-base-extra"]
dockerfile: release/ray_release/byod/byod.Dockerfile
srcs:
  - python/deplocks/base_extra_testdeps/ray_base_extra_testdeps_cuda_py$PYTHON_VERSION.lock
build_args:
  - BASE_IMAGE=cr.ray.io/rayproject/$IMAGE_TYPE-py$PYTHON_VERSION-cu$CUDA_VERSION-base-extra
  - PYTHON_VERSION
  - EXTRA_VARIANT=cuda_
tags:
  - cr.ray.io/rayproject/$IMAGE_TYPE-py$PYTHON_VERSION-cu$CUDA_VERSION-base-extra-testdeps
