cloud_id: {{ env["ANYSCALE_CLOUD_ID"] }}
region: us-west-2

# 4 g4dn.4xlarge nodes --> 64 CPUs, 4 GPUs
head_node_type:
  name: head_node_type
  instance_type: g4dn.4xlarge

worker_node_types:
- name: gpu_worker
  instance_type: g4dn.4xlarge
  min_workers: 3
  max_workers: 3
  use_spot: false

aws:
  TagSpecifications:
    - ResourceType: "instance"
      Tags:
        - Key: ttl-hours
          Value: '24'