[project]
name = "default"
version = "0.1.0"
description = "Langchain with Ray Serve"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.115.12",
    "langchain==1.0.5",
    "langchain-mcp-adapters==0.1.12",
    "langchain-openai==1.0.2",
    "langgraph==1.0.3",
    "openai==2.7.2",
    "uvicorn==0.38.0",
]
