build_arg_sets:
  py310:
    PYTHON_VERSION: "3.10"
    PYTHON_SHORT: "310"
  py312:
    PYTHON_VERSION: "3.12"
    PYTHON_SHORT: "312"

depsets:
  - name: serve_ci_depset_${PYTHON_SHORT}
    operation: expand
    depsets:
      - ray_img_depset_${PYTHON_SHORT}
    requirements:
      - python/requirements/serve/serve-requirements.txt
    constraints:
      - /tmp/ray-deps/requirements_compiled_py3.13.txt
    output: python/deplocks/ci/serve_base_depset_py${PYTHON_VERSION}.lock
    append_flags:
      - --index https://download.pytorch.org/whl/cpu
      - --python-version=${PYTHON_VERSION}
      - --python-platform=linux
      - --unsafe-package ray
      - --override python/requirements/serve/serve-overrides.txt
    build_arg_sets:
      - py310
      - py312

  - name: serve_tracing_ci_depset_${PYTHON_SHORT}
    operation: expand
    depsets:
      - serve_ci_depset_${PYTHON_SHORT}
    constraints:
      - /tmp/ray-deps/requirements_compiled_py3.13.txt
    output: python/deplocks/ci/serve_tracing_depset_py${PYTHON_VERSION}.lock
    append_flags:
      - --python-version=${PYTHON_VERSION}
      - --python-platform=linux
      - --unsafe-package ray
      - --override python/requirements/serve/tracing-reqs.txt
      - --override python/requirements/serve/serve-overrides.txt
    build_arg_sets:
      - py310
