build_arg_sets:
  py39:
    PYTHON_VERSION: "3.9"
  py312:
    PYTHON_VERSION: "3.12"


depsets:
  - name: demo_depset_${PYTHON_VERSION}
    operation: compile
    requirements:
      - demo.in
    output: demo_py${PYTHON_VERSION}.lock
    append_flags:
      - --python-version=${PYTHON_VERSION}
      - --python-platform=linux
    build_arg_sets:
      - py39
