build_arg_sets:
  py39:
    PYTHON_VERSION: "3.9"
  py310:
    PYTHON_VERSION: "3.10"
  py312:
    PYTHON_VERSION: "3.12"


depsets:
  - name: docbuild_depset_${PYTHON_VERSION}
    operation: compile
    depsets:
      - ray_img_depset_${PYTHON_VERSION}
    requirements:
      - doc/requirements-doc.txt
    output: python/deplocks/docs/docbuild_depset_py${PYTHON_VERSION}.lock
    append_flags:
      - --python-version=${PYTHON_VERSION}
      - --python-platform=linux
      - --unsafe-package ray
    build_arg_sets:
      - py39
      - py310
      - py312
