depsets:
  - name: large_test_depset
    operation: compile
    requirements:
      - ci/raydepsets/tests/test_data/test_python_depset.lock
    output: ci/raydepsets/tests/test_data/test_python_depset.lock
  - name: relax_test_depset
    operation: relax
    source_depset: large_test_depset
    drop_package: aiohttp
    output: python/deplocks/test/relax_test_depset.lock
