base_image: {{ env["RAY_IMAGE_NIGHTLY_CPU"] | default("anyscale/ray:nightly-py37") }}
debian_packages: []

python:
  pip_packages: ["dask[complete]", tqdm, scipy, xarray, zarr, boto, s3fs, pyarrow, pytest]
  conda_packages: []

post_build_cmds:
  # - pip install fastparquet
  - pip3 uninstall -y ray
  - pip3 install -U pytest
  - pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  - pip3 install -U ray[default]
  - echo {{env["DATESTAMP"]}}
  - {{ env["RAY_WHEELS_SANITY_CHECK"] | default("echo No Ray wheels sanity check") }}
