name: ray-cicd-cron
artifacts_bucket: ray-ci-artifact-branch-public
ci_temp: s3://ray-ci-artifact-branch-public/ci-temp/
ci_work_repo: 029272617770.dkr.ecr.us-west-2.amazonaws.com/rayproject/citemp
forge_prefix: cr.ray.io/rayproject/
builder_queues:
  builder-x86_64: builder_queue_branch
  builder-aarch64: builder_queue_arm64_branch
runner_queues:
  default: runner_queue_small_branch
buildkite_dirs:
  - .buildkite/cicd-cron
env:
  BUILDKITE_BAZEL_CACHE_URL: https://bazel-cache-dev.s3.us-west-2.amazonaws.com
hook_env_keys:
  - RAYCI_CHECKOUT_DIR
docker_plugin:
  allow_mount_buildkite_agent: true
