[package]
name = "ray-observability"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Observability and event recording for Ray"

[dependencies]
ray-util = { workspace = true }
ray-stats = { workspace = true }
ray-common = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
nix = { workspace = true }
