base_image: {{ env["RAY_IMAGE_ML_NIGHTLY_GPU"] | default("anyscale/ray-ml:nightly-py37-gpu") }}

debian_packages:
  - curl

python:
  pip_packages:
    - tblib
    # Need to have in pip_packages so it is installed on the driver.
    - git+https://github.com/ray-project/ray_lightning#ray_lightning
    - torch==1.11.0
  conda_packages: []

post_build_cmds:
  # Upgrade the Ray Lightning version in post build commands, otherwise it will be cached in the Anyscale Docker image.
  - echo {{ env["TIMESTAMP"] }}
  - pip3 install -U --force-reinstall pytorch-lightning lightning-bolts
  - pip uninstall ray_lightning -y # Uninstall first so pip does a reinstall.
  - pip3 install -U --no-cache-dir git+https://github.com/ray-project/ray_lightning#ray_lightning
  - pip3 install --force-reinstall torch==1.11.0
  - pip3 install --force-reinstall torchvision==0.12.0
  - pip uninstall -y ray || true && pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  - {{ env["RAY_WHEELS_SANITY_CHECK"] | default("echo No Ray wheels sanity check") }}
