cluster_name: single-node-benchmarks
min_workers: 0
max_workers: 0

upscaling_speed: 9999999

provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a

auth:
    ssh_user: ubuntu

available_node_types:
    head_node:
        node_config:
            InstanceType: m4.16xlarge
            ImageId: ami-098555c9b343eb09c 
        resources:
          node: 1
        max_workers: 999999
    worker_node:
        node_config:
            InstanceType: m4.xlarge
            ImageId: ami-098555c9b343eb09c 

head_node_type: head_node

worker_default_node_type: worker_node

setup_commands:
  - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/releases/1.4.0/6ac5e0e5ad45070e27c77aca7267bcee30cc4b4a/ray-1.4.0-cp37-cp37m-manylinux2014_x86_64.whl
  - pip install numpy tqdm
  - sudo bash -c 'rm -rf /etc/security/limits.d; echo "* soft nofile 1000000" >> /etc/security/limits.conf; echo "* hard nofile 1000000" >> /etc/security/limits.conf;'

idle_timeout_minutes: 5

head_start_ray_commands:
    - ray stop
    - ulimit -n 1000000; ray start --head --port=6379 --object-manager-port=8076 --object-store-memory=128000000000 --autoscaling-config=~/ray_bootstrap_config.yaml
