base_image: "anyscale/ray:nightly-py39"
debian_packages: []
env_vars: {"RAY_MAX_LIMIT_FROM_API_SERVER": "1000000000", "RAY_MAX_LIMIT_FROM_DATA_SOURCE":"1000000000", "RAY_gcs_server_rpc_client_thread_num": "4", "RAY_gcs_server_rpc_server_thread_num": "4" }

python:
  pip_packages: []
  conda_packages: []

post_build_cmds:
  - pip3 uninstall -y ray && pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  - pip3 install -U ray[default]
  - {{ env["RAY_WHEELS_SANITY_CHECK"] | default("echo No Ray wheels sanity check") }}
