name: "rayturbobuild"
froms: ["cr.ray.io/rayproject/oss-ci-base_build"]
dockerfile: anyscale/ci/docker/rayturbo.build.Dockerfile
srcs:
  - python/requirements.txt
  - python/requirements_compiled.txt
  - python/requirements/test-requirements.txt
  - anyscale/docker/runtime-requirements.txt
  - anyscale/docker/runtime-test-requirements.txt
build_args:
  - DOCKER_IMAGE_BASE_BUILD=cr.ray.io/rayproject/oss-ci-base_build
tags:
  - cr.ray.io/rayproject/rayturbobuild
