[package]
name = "actor"
version = "0.0.0"
authors = ["Jonathan Chuang"]
license = "Apache-2.0"
edition = "2018"
publish = true

[dependencies]
# ray-rs = "0.0.0"
ray-rs = { path = "../../ray-rs", features = ["async"] }
serde = "1.0.132"
tokio = { version = "1.16.1", features = ["sync", "time", "macros"] }
#path = "../../../../tokio/tokio",version = "1.16.1",
tokio-time-sleep = { path = "./tokio-time-sleep" }

[build-dependencies]
rustc_version = "0.4.0"

[lib]
crate-type = ["rlib", "cdylib"]
