release_byod:
  ray_ecr: rayproject
  ray_cr_repo: ray
  ray_ml_cr_repo: ray-ml
  ray_llm_cr_repo: ray-llm
  byod_ecr: 029272617770.dkr.ecr.us-west-2.amazonaws.com
  byod_ecr_region: us-west-2
  aws_cr: 029272617770.dkr.ecr.us-west-2.amazonaws.com
  gcp_cr: us-west1-docker.pkg.dev/anyscale-oss-ci
  aws2gce_credentials: release/aws2gce_iam.json
ci_pipeline:
  premerge:
    - 0189942e-0876-4b8f-80a4-617f988ec59b  # premerge
    - 018f4f1e-1b73-4906-9802-92422e3badaa  # microcheck
  postmerge:
    - 0189e759-8c96-4302-b6b5-b4274406bf89  # postmerge
    - 018e0f94-ccb6-45c2-b072-1e624fe9a404  # postmerge-macos
    - 018af6d3-58e1-463f-90ec-d9aa4a4f57f1  # release
    - 018773ff-b5db-4dcb-8a49-1c6492b4d0f4  # bisect
  buildkite_secret: ray_ci_buildkite_token
state_machine:
  pr:
    aws_bucket: ray-ci-pr-results
  branch:
    aws_bucket: ray-ci-results
release_image_step:
  ray: anyscalebuild
  ray_ml: anyscalemlbuild
  ray_llm: anyscalellmbuild
