release_byod:
  ray_ecr: 830883877497.dkr.ecr.us-west-2.amazonaws.com/anyscale
  ray_cr_repo: runtime
  ray_ml_cr_repo: runtime-ml
  byod_ecr: 830883877497.dkr.ecr.us-west-2.amazonaws.com
  aws_cr: 830883877497.dkr.ecr.us-west-2.amazonaws.com
  gcp_cr: us-west1-docker.pkg.dev/anyscale-oss-ci
  aws2gce_credentials: release/aws2gce_runtime_iam.json
state_machine:
  aws_bucket: ray-ci-results
