[package]
name = "ray-common"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Common types for Ray (IDs, Status, Config, scheduling)"

[dependencies]
ray-proto = { workspace = true }
ray-util = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
tempfile = { workspace = true }
